--STEP 1: DATABASE, SCHEMA & MULTI-CLUSTER WAREHOUSE

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.PATIENTS;

CREATE WAREHOUSE IF NOT EXISTS HEALTH_WH
WITH
    WAREHOUSE_SIZE = 'SMALL'
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = 'STANDARD'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Healthcare Patient Analytics Project Warehouse';


USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

SHOW DATABASES LIKE 'HEALTHCARE_DB';

SHOW WAREHOUSES LIKE 'HEALTH_WH';

SELECT
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA,
    CURRENT_WAREHOUSE() AS CURRENT_WAREHOUSE;