
USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

DROP STAGE IF EXISTS HEALTHCARE_INTERNAL_STAGE;

CREATE STAGE HEALTHCARE_INTERNAL_STAGE
    COMMENT = 'Internal stage for healthcare project source files';

SHOW STAGES;

LIST @HEALTHCARE_INTERNAL_STAGE;