
USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;



CREATE FILE FORMAT IF NOT EXISTS healthcare_json_format
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;


SHOW FILE FORMATS IN SCHEMA HEALTHCARE_DB.PATIENTS;



COPY INTO appointment_api_logs
(
    payload
)
FROM @HEALTHCARE_INTERNAL_STAGE/appointment_logs.json
FILE_FORMAT = (
    FORMAT_NAME = 'HEALTHCARE_DB.PATIENTS.HEALTHCARE_JSON_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';


SELECT COUNT(*) AS json_records
FROM appointment_api_logs;