-- STEP 1 — Environment Setup
CREATE DATABASE RETAIL_DW;

SHOW DATABASES;

USE DATABASE RETAIL_DW;

CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;
CREATE SCHEMA STAGING;

SHOW SCHEMAS;

-- Create the Warehouse
CREATE WAREHOUSE RETAIL_WH
WITH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_WH;

USE DATABASE RETAIL_DW;

SELECT CURRENT_DATABASE();

SELECT CURRENT_WAREHOUSE();

