USE WAREHOUSE RETAIL_WH;

USE DATABASE RETAIL_DW;

USE SCHEMA BRONZE;

SELECT CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE();

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

SHOW FILE FORMATS;

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = RETAIL_CSV_FORMAT;

SHOW STAGES;

LIST @RETAIL_STAGE;

SELECT
    $1 AS order_id,
    $2 AS customer_name,
    $3 AS product,
    $4 AS amount,
    $5 AS order_date
FROM @RETAIL_STAGE
(
    FILE_FORMAT => 'RETAIL_CSV_FORMAT'
)
LIMIT 10;