-- STEP 9 — Time Travel
USE DATABASE RETAIL_DW;
USE WAREHOUSE RETAIL_WH;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE SALES_TIME_TRAVEL_TEST AS
SELECT *
FROM SALES_RAW;

SELECT COUNT(*) AS row_count
FROM SALES_TIME_TRAVEL_TEST;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
ORDER BY order_id;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
ORDER BY order_id;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
ORDER BY order_id;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
WHERE order_id = 1001;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
WHERE order_id = 1001;

SELECT *
FROM SALES_TIME_TRAVEL_TEST
AT (
    OFFSET => -60
)
WHERE order_id = 1001;


INSERT INTO SALES_TIME_TRAVEL_TEST
SELECT *
FROM SALES_TIME_TRAVEL_TEST
AT (
    OFFSET => -300
)
WHERE order_id = 1001;



-- zero copy clonning
CREATE DATABASE RETAIL_QA CLONE RETAIL_DW;

SHOW DATABASES LIKE 'RETAIL_QA';

SHOW TABLES IN DATABASE RETAIL_QA;

SELECT *
FROM RETAIL_QA.BRONZE.SALES_RAW
LIMIT 10;

SELECT COUNT(*)
FROM RETAIL_QA.BRONZE.SALES_RAW;


-- Resource Moniter
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR RETAIL_RESOURCE_MONITOR
WITH
    CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;


ALTER WAREHOUSE RETAIL_WH
SET RESOURCE_MONITOR = RETAIL_RESOURCE_MONITOR;