-- STEP 10 — Security & Data Sharing
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS RETAIL_ANALYST;

CREATE ROLE IF NOT EXISTS RETAIL_REPORTING;

SHOW ROLES LIKE 'RETAIL_%';

GRANT USAGE
ON DATABASE RETAIL_DW
TO ROLE RETAIL_ANALYST;

GRANT USAGE
ON DATABASE RETAIL_DW
TO ROLE RETAIL_REPORTING;

GRANT USAGE
ON SCHEMA RETAIL_DW.GOLD
TO ROLE RETAIL_ANALYST;

GRANT USAGE
ON SCHEMA RETAIL_DW.GOLD
TO ROLE RETAIL_REPORTING;

GRANT USAGE
ON WAREHOUSE RETAIL_WH
TO ROLE RETAIL_ANALYST;

GRANT USAGE
ON WAREHOUSE RETAIL_WH
TO ROLE RETAIL_ANALYST;

GRANT SELECT
ON TABLE RETAIL_DW.GOLD.SALES_SUMMARY_V2
TO ROLE RETAIL_ANALYST;

SHOW GRANTS TO ROLE RETAIL_ANALYST;

SHOW GRANTS TO ROLE RETAIL_REPORTING;

USE DATABASE RETAIL_DW;
USE SCHEMA GOLD;

CREATE OR REPLACE VIEW SALES_REPORTING_VIEW AS
SELECT
    product,
    total_orders,
    total_sales,
    average_order_value,
    minimum_order_value,
    maximum_order_value
FROM SALES_SUMMARY_V2;

SELECT *
FROM SALES_REPORTING_VIEW
ORDER BY total_sales DESC;

CREATE OR REPLACE SECURE VIEW SECURE_SALES_REPORTING AS
SELECT
    product,
    total_orders,
    total_sales,
    average_order_value
FROM SALES_SUMMARY_V2;

SELECT *
FROM SECURE_SALES_REPORTING;

GRANT SELECT
ON VIEW RETAIL_DW.GOLD.SECURE_SALES_REPORTING
TO ROLE RETAIL_REPORTING;

CREATE OR REPLACE MATERIALIZED VIEW MV_PRODUCT_SALES
AS
SELECT
    product,
    SUM(amount) AS total_sales,
    COUNT(*) AS total_orders
FROM RETAIL_DW.SILVER.SALES_FINAL
GROUP BY product;

SELECT *
FROM MV_PRODUCT_SALES
ORDER BY total_sales DESC;

SHOW VIEWS IN SCHEMA RETAIL_DW.GOLD;

SHOW MATERIALIZED VIEWS IN SCHEMA RETAIL_DW.GOLD;


-- DATA SHARING
USE ROLE ACCOUNTADMIN;

CREATE SHARE RETAIL_SALES_SHARE;

SHOW SHARES;

GRANT USAGE
ON DATABASE RETAIL_DW
TO SHARE RETAIL_SALES_SHARE;

GRANT USAGE
ON SCHEMA RETAIL_DW.GOLD
TO SHARE RETAIL_SALES_SHARE;

GRANT SELECT
ON VIEW RETAIL_DW.GOLD.SECURE_SALES_REPORTING
TO SHARE RETAIL_SALES_SHARE;

SHOW GRANTS TO SHARE RETAIL_SALES_SHARE;

SELECT *
FROM RETAIL_DW.GOLD.MV_PRODUCT_SALES
ORDER BY total_sales DESC;

SHOW GRANTS TO ROLE RETAIL_ANALYST;