USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

ALTER TABLE staging_appointments
CLUSTER BY (appointment_date, department);

SHOW TABLES LIKE 'STAGING_APPOINTMENTS';

SELECT
    SYSTEM$CLUSTERING_INFORMATION(
        'HEALTHCARE_DB.PATIENTS.STAGING_APPOINTMENTS'
    ) AS clustering_information;