USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

ALTER TABLE staging_appointments
ADD SEARCH OPTIMIZATION
ON EQUALITY(patient_id, doctor_id, status);

SHOW TABLES LIKE 'STAGING_APPOINTMENTS';

DESCRIBE TABLE staging_appointments;