USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

CREATE STAGE IF NOT EXISTS healthcare_s3_stage
URL = 's3://YOUR-BUCKET-NAME/healthcare/'
COMMENT = 'External AWS S3 stage for healthcare incoming data';

SHOW STAGES IN SCHEMA HEALTHCARE_DB.PATIENTS;