USE DATABASE HEALTHCARE_DB;

USE SCHEMA PATIENTS;

USE WAREHOUSE HEALTH_WH;

CREATE PIPE IF NOT EXISTS healthcare_appointment_pipe
AUTO_INGEST = FALSE
AS
COPY INTO staging_appointments
FROM @healthcare_s3_stage
FILE_FORMAT = (
    FORMAT_NAME = 'HEALTHCARE_DB.PATIENTS.HEALTHCARE_CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';

SHOW PIPES IN SCHEMA HEALTHCARE_DB.PATIENTS;