

CREATE ROLE IF NOT EXISTS HEALTHCARE_ANALYST;

CREATE ROLE IF NOT EXISTS HEALTHCARE_DOCTOR;


GRANT USAGE
ON DATABASE HEALTHCARE_DB
TO ROLE HEALTHCARE_ANALYST;

GRANT USAGE
ON DATABASE HEALTHCARE_DB
TO ROLE HEALTHCARE_DOCTOR;

GRANT USAGE
ON SCHEMA HEALTHCARE_DB.PATIENTS
TO ROLE HEALTHCARE_ANALYST;

GRANT USAGE
ON SCHEMA HEALTHCARE_DB.PATIENTS
TO ROLE HEALTHCARE_DOCTOR;


GRANT USAGE
ON WAREHOUSE HEALTH_WH
TO ROLE HEALTHCARE_ANALYST;

GRANT USAGE
ON WAREHOUSE HEALTH_WH
TO ROLE HEALTHCARE_DOCTOR;


GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.PATIENT_MASTER
TO ROLE HEALTHCARE_ANALYST;

GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.PATIENT_MASTER
TO ROLE HEALTHCARE_DOCTOR;



GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.STAGING_APPOINTMENTS
TO ROLE HEALTHCARE_ANALYST;

GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.STAGING_APPOINTMENTS
TO ROLE HEALTHCARE_DOCTOR;

GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.DOCTOR_MASTER
TO ROLE HEALTHCARE_ANALYST;

GRANT SELECT
ON TABLE HEALTHCARE_DB.PATIENTS.DOCTOR_MASTER
TO ROLE HEALTHCARE_DOCTOR;


SHOW ROLES LIKE 'HEALTHCARE_%';